In [1]:
import numpy as np

In [9]:
#Variables
c_o=344      #Velocidad del sonido
f_max=2420   #Frecuencia máxima
f_o=1385      #Frecuencia mínima
N=7 

#n y m son igual a N, ya que, range() ya se encarga de contar desde el 0 hasta N-1
n = N
m = N
nm2 = np.array([[0 for x in range(n)] for y in range(m)])

#Calcular s_[n,m]
for i in range(m):
    for j in range(n):
        nm2[i][j] = i**2+j**2
        snm= nm2%N

print("n^2 + m^2:")
print(nm2)
print("Las secuencias de residuos cuadráticos son:")
print(snm)

n^2 + m^2:
[[ 0  1  4  9 16 25 36]
 [ 1  2  5 10 17 26 37]
 [ 4  5  8 13 20 29 40]
 [ 9 10 13 18 25 34 45]
 [16 17 20 25 32 41 52]
 [25 26 29 34 41 50 61]
 [36 37 40 45 52 61 72]]
Las secuencias de residuos cuadráticos son:
[[0 1 4 2 2 4 1]
 [1 2 5 3 3 5 2]
 [4 5 1 6 6 1 5]
 [2 3 6 4 4 6 3]
 [2 3 6 4 4 6 3]
 [4 5 1 6 6 1 5]
 [1 2 5 3 3 5 2]]


In [10]:
#Calcular d_[n,m]
dnm= (snm*c_o)/(2*N*f_o)
print("Las profundidades de las ranuras son:")
print(np.round(dnm,5), "m")

Las profundidades de las ranuras son:
[[0.      0.01774 0.07096 0.03548 0.03548 0.07096 0.01774]
 [0.01774 0.03548 0.08871 0.05322 0.05322 0.08871 0.03548]
 [0.07096 0.08871 0.01774 0.10645 0.10645 0.01774 0.08871]
 [0.03548 0.05322 0.10645 0.07096 0.07096 0.10645 0.05322]
 [0.03548 0.05322 0.10645 0.07096 0.07096 0.10645 0.05322]
 [0.07096 0.08871 0.01774 0.10645 0.10645 0.01774 0.08871]
 [0.01774 0.03548 0.08871 0.05322 0.05322 0.08871 0.03548]] m


In [11]:
#Calcular w
w= c_o/(2*f_max)
print("El ancho de las ranuras es:", np.round(w,5), "mm")

El ancho de las ranuras es: 0.07107 mm
